[registry]
url = "https://anchor.projectserum.com"

[provider]
wallet = "~/.config/solana/id.json"
cluster="localnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
